/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.petrasolar.nms.protocol.dnp3;

public final class AnalogQuality {
  public final static AnalogQuality AQ_ONLINE = new AnalogQuality("AQ_ONLINE", javadnp3JNI.AQ_ONLINE_get());
  public final static AnalogQuality AQ_RESTART = new AnalogQuality("AQ_RESTART", javadnp3JNI.AQ_RESTART_get());
  public final static AnalogQuality AQ_COMM_LOST = new AnalogQuality("AQ_COMM_LOST", javadnp3JNI.AQ_COMM_LOST_get());
  public final static AnalogQuality AQ_REMOTE_FORCED_DATA = new AnalogQuality("AQ_REMOTE_FORCED_DATA", javadnp3JNI.AQ_REMOTE_FORCED_DATA_get());
  public final static AnalogQuality AQ_LOCAL_FORCED_DATA = new AnalogQuality("AQ_LOCAL_FORCED_DATA", javadnp3JNI.AQ_LOCAL_FORCED_DATA_get());
  public final static AnalogQuality AQ_OVERRANGE = new AnalogQuality("AQ_OVERRANGE", javadnp3JNI.AQ_OVERRANGE_get());
  public final static AnalogQuality AQ_REFERENCE_CHECK = new AnalogQuality("AQ_REFERENCE_CHECK", javadnp3JNI.AQ_REFERENCE_CHECK_get());
  public final static AnalogQuality AQ_RESERVED = new AnalogQuality("AQ_RESERVED", javadnp3JNI.AQ_RESERVED_get());

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static AnalogQuality swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + AnalogQuality.class + " with value " + swigValue);
  }

  private AnalogQuality(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private AnalogQuality(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private AnalogQuality(String swigName, AnalogQuality swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static AnalogQuality[] swigValues = { AQ_ONLINE, AQ_RESTART, AQ_COMM_LOST, AQ_REMOTE_FORCED_DATA, AQ_LOCAL_FORCED_DATA, AQ_OVERRANGE, AQ_REFERENCE_CHECK, AQ_RESERVED };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

