/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.petrasolar.nms.protocol.dnp3;

public class Analog extends DoublePoint {
  private long swigCPtr;

  protected Analog(long cPtr, boolean cMemoryOwn) {
    super(javadnp3JNI.Analog_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Analog obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        javadnp3JNI.delete_Analog(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  protected void swigDirectorDisconnect() {
    swigCMemOwn = false;
    delete();
  }

  public void swigReleaseOwnership() {
    swigCMemOwn = false;
    javadnp3JNI.Analog_change_ownership(this, swigCPtr, false);
  }

  public void swigTakeOwnership() {
    swigCMemOwn = true;
    javadnp3JNI.Analog_change_ownership(this, swigCPtr, true);
  }

  public Analog() {
    this(javadnp3JNI.new_Analog__SWIG_0(), true);
    javadnp3JNI.Analog_director_connect(this, swigCPtr, swigCMemOwn, true);
  }

  public Analog(double aVal, short aQuality) {
    this(javadnp3JNI.new_Analog__SWIG_1(aVal, aQuality), true);
    javadnp3JNI.Analog_director_connect(this, swigCPtr, swigCMemOwn, true);
  }

  public Analog(double aVal) {
    this(javadnp3JNI.new_Analog__SWIG_2(aVal), true);
    javadnp3JNI.Analog_director_connect(this, swigCPtr, swigCMemOwn, true);
  }

  public double get_analog() {
    return javadnp3JNI.Analog_get_analog(swigCPtr, this);
  }

  public double set_analog(double aValue) {
    return javadnp3JNI.Analog_set_analog(swigCPtr, this, aValue);
  }

  public final static DataTypes MeasEnum = DataTypes.swigToEnum(javadnp3JNI.Analog_MeasEnum_get());
  public final static int ONLINE = javadnp3JNI.Analog_ONLINE_get();
}
