/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.petrasolar.nms.protocol.dnp3;

public final class BinaryQuality {
  public final static BinaryQuality BQ_ONLINE = new BinaryQuality("BQ_ONLINE", javadnp3JNI.BQ_ONLINE_get());
  public final static BinaryQuality BQ_RESTART = new BinaryQuality("BQ_RESTART", javadnp3JNI.BQ_RESTART_get());
  public final static BinaryQuality BQ_COMM_LOST = new BinaryQuality("BQ_COMM_LOST", javadnp3JNI.BQ_COMM_LOST_get());
  public final static BinaryQuality BQ_REMOTE_FORCED_DATA = new BinaryQuality("BQ_REMOTE_FORCED_DATA", javadnp3JNI.BQ_REMOTE_FORCED_DATA_get());
  public final static BinaryQuality BQ_LOCAL_FORCED_DATA = new BinaryQuality("BQ_LOCAL_FORCED_DATA", javadnp3JNI.BQ_LOCAL_FORCED_DATA_get());
  public final static BinaryQuality BQ_CHATTER_FILTER = new BinaryQuality("BQ_CHATTER_FILTER", javadnp3JNI.BQ_CHATTER_FILTER_get());
  public final static BinaryQuality BQ_RESERVED = new BinaryQuality("BQ_RESERVED", javadnp3JNI.BQ_RESERVED_get());
  public final static BinaryQuality BQ_STATE = new BinaryQuality("BQ_STATE", javadnp3JNI.BQ_STATE_get());

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static BinaryQuality swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + BinaryQuality.class + " with value " + swigValue);
  }

  private BinaryQuality(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private BinaryQuality(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private BinaryQuality(String swigName, BinaryQuality swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static BinaryQuality[] swigValues = { BQ_ONLINE, BQ_RESTART, BQ_COMM_LOST, BQ_REMOTE_FORCED_DATA, BQ_LOCAL_FORCED_DATA, BQ_CHATTER_FILTER, BQ_RESERVED, BQ_STATE };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

