/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.petrasolar.nms.protocol.dnp3;

public class BinaryOutput extends CommandRequest {
  private long swigCPtr;

  protected BinaryOutput(long cPtr, boolean cMemoryOwn) {
    super(javadnp3JNI.BinaryOutput_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(BinaryOutput obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        javadnp3JNI.delete_BinaryOutput(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public BinaryOutput() {
    this(javadnp3JNI.new_BinaryOutput__SWIG_0(), true);
  }

  public BinaryOutput(ControlCode aCode, short aCount, long aOnTime, long aOffTime) {
    this(javadnp3JNI.new_BinaryOutput__SWIG_1(aCode.swigValue(), aCount, aOnTime, aOffTime), true);
  }

  public BinaryOutput(ControlCode aCode, short aCount, long aOnTime) {
    this(javadnp3JNI.new_BinaryOutput__SWIG_2(aCode.swigValue(), aCount, aOnTime), true);
  }

  public BinaryOutput(ControlCode aCode, short aCount) {
    this(javadnp3JNI.new_BinaryOutput__SWIG_3(aCode.swigValue(), aCount), true);
  }

  public BinaryOutput(ControlCode aCode) {
    this(javadnp3JNI.new_BinaryOutput__SWIG_4(aCode.swigValue()), true);
  }

  public ControlCode GetCode() {
    return ControlCode.swigToEnum(javadnp3JNI.BinaryOutput_GetCode(swigCPtr, this));
  }

  public void setMRawCode(short value) {
    javadnp3JNI.BinaryOutput_mRawCode_set(swigCPtr, this, value);
  }

  public short getMRawCode() {
    return javadnp3JNI.BinaryOutput_mRawCode_get(swigCPtr, this);
  }

  public void setMCount(short value) {
    javadnp3JNI.BinaryOutput_mCount_set(swigCPtr, this, value);
  }

  public short getMCount() {
    return javadnp3JNI.BinaryOutput_mCount_get(swigCPtr, this);
  }

  public void setMOnTimeMS(long value) {
    javadnp3JNI.BinaryOutput_mOnTimeMS_set(swigCPtr, this, value);
  }

  public long getMOnTimeMS() {
    return javadnp3JNI.BinaryOutput_mOnTimeMS_get(swigCPtr, this);
  }

  public void setMOffTimeMS(long value) {
    javadnp3JNI.BinaryOutput_mOffTimeMS_set(swigCPtr, this, value);
  }

  public long getMOffTimeMS() {
    return javadnp3JNI.BinaryOutput_mOffTimeMS_get(swigCPtr, this);
  }

  public String ToString() {
    return javadnp3JNI.BinaryOutput_ToString(swigCPtr, this);
  }

  public boolean boEqual(BinaryOutput arRHS) {
    return javadnp3JNI.BinaryOutput_boEqual(swigCPtr, this, BinaryOutput.getCPtr(arRHS), arRHS);
  }

  public final static CommandTypes EnumType = CommandTypes.swigToEnum(javadnp3JNI.BinaryOutput_EnumType_get());
}
