/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.petrasolar.nms.protocol.dnp3;

public class ClassMask {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected ClassMask(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ClassMask obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        javadnp3JNI.delete_ClassMask(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public ClassMask(boolean c1, boolean c2, boolean c3) {
    this(javadnp3JNI.new_ClassMask__SWIG_0(c1, c2, c3), true);
  }

  public ClassMask() {
    this(javadnp3JNI.new_ClassMask__SWIG_1(), true);
  }

  public void setClass1(boolean value) {
    javadnp3JNI.ClassMask_class1_set(swigCPtr, this, value);
  }

  public boolean getClass1() {
    return javadnp3JNI.ClassMask_class1_get(swigCPtr, this);
  }

  public void setClass2(boolean value) {
    javadnp3JNI.ClassMask_class2_set(swigCPtr, this, value);
  }

  public boolean getClass2() {
    return javadnp3JNI.ClassMask_class2_get(swigCPtr, this);
  }

  public void setClass3(boolean value) {
    javadnp3JNI.ClassMask_class3_set(swigCPtr, this, value);
  }

  public boolean getClass3() {
    return javadnp3JNI.ClassMask_class3_get(swigCPtr, this);
  }

  public static int GetMask(boolean c1, boolean c2, boolean c3) {
    return javadnp3JNI.ClassMask_GetMask(c1, c2, c3);
  }

  public boolean IsEnabled() {
    return javadnp3JNI.ClassMask_IsEnabled(swigCPtr, this);
  }

}
