/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.petrasolar.nms.protocol.dnp3;

public class CommandRequest {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected CommandRequest(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(CommandRequest obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        javadnp3JNI.delete_CommandRequest(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public CommandTypes GetType() {
    return CommandTypes.swigToEnum(javadnp3JNI.CommandRequest_GetType(swigCPtr, this));
  }

  public void setMStatus(CommandStatus value) {
    javadnp3JNI.CommandRequest_mStatus_set(swigCPtr, this, value.swigValue());
  }

  public CommandStatus getMStatus() {
    return CommandStatus.swigToEnum(javadnp3JNI.CommandRequest_mStatus_get(swigCPtr, this));
  }

}
