/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.petrasolar.nms.protocol.dnp3;

public final class CommandTypes {
  public final static CommandTypes CT_BINARY_OUTPUT = new CommandTypes("CT_BINARY_OUTPUT");
  public final static CommandTypes CT_SETPOINT = new CommandTypes("CT_SETPOINT");
  public final static CommandTypes CT_NONE = new CommandTypes("CT_NONE");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static CommandTypes swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + CommandTypes.class + " with value " + swigValue);
  }

  private CommandTypes(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private CommandTypes(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private CommandTypes(String swigName, CommandTypes swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static CommandTypes[] swigValues = { CT_BINARY_OUTPUT, CT_SETPOINT, CT_NONE };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

