/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.petrasolar.nms.protocol.dnp3;

public final class CommandModes {
  public final static CommandModes CM_SBO_ONLY = new CommandModes("CM_SBO_ONLY");
  public final static CommandModes CM_DO_ONLY = new CommandModes("CM_DO_ONLY");
  public final static CommandModes CM_SBO_OR_DO = new CommandModes("CM_SBO_OR_DO");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static CommandModes swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + CommandModes.class + " with value " + swigValue);
  }

  private CommandModes(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private CommandModes(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private CommandModes(String swigName, CommandModes swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static CommandModes[] swigValues = { CM_SBO_ONLY, CM_DO_ONLY, CM_SBO_OR_DO };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

