/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.petrasolar.nms.protocol.dnp3;

public class ControlStatus extends BoolDataPoint {
  private long swigCPtr;

  protected ControlStatus(long cPtr, boolean cMemoryOwn) {
    super(javadnp3JNI.ControlStatus_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ControlStatus obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        javadnp3JNI.delete_ControlStatus(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  protected void swigDirectorDisconnect() {
    swigCMemOwn = false;
    delete();
  }

  public void swigReleaseOwnership() {
    swigCMemOwn = false;
    javadnp3JNI.ControlStatus_change_ownership(this, swigCPtr, false);
  }

  public void swigTakeOwnership() {
    swigCMemOwn = true;
    javadnp3JNI.ControlStatus_change_ownership(this, swigCPtr, true);
  }

  public ControlStatus(boolean aValue, short aQuality) {
    this(javadnp3JNI.new_ControlStatus__SWIG_0(aValue, aQuality), true);
    javadnp3JNI.ControlStatus_director_connect(this, swigCPtr, swigCMemOwn, true);
  }

  public ControlStatus(boolean aValue) {
    this(javadnp3JNI.new_ControlStatus__SWIG_1(aValue), true);
    javadnp3JNI.ControlStatus_director_connect(this, swigCPtr, swigCMemOwn, true);
  }

  public ControlStatus() {
    this(javadnp3JNI.new_ControlStatus__SWIG_2(), true);
    javadnp3JNI.ControlStatus_director_connect(this, swigCPtr, swigCMemOwn, true);
  }

  public boolean get_controlstatus() {
    return javadnp3JNI.ControlStatus_get_controlstatus(swigCPtr, this);
  }

  public boolean set_controlstatus(boolean aValue) {
    return javadnp3JNI.ControlStatus_set_controlstatus(swigCPtr, this, aValue);
  }

  public final static DataTypes MeasEnum = DataTypes.swigToEnum(javadnp3JNI.ControlStatus_MeasEnum_get());
  public final static int ONLINE = javadnp3JNI.ControlStatus_ONLINE_get();
}
