/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.petrasolar.nms.protocol.dnp3;

public final class ControlCode {
  public final static ControlCode CC_NULL = new ControlCode("CC_NULL", javadnp3JNI.CC_NULL_get());
  public final static ControlCode CC_PULSE = new ControlCode("CC_PULSE", javadnp3JNI.CC_PULSE_get());
  public final static ControlCode CC_LATCH_ON = new ControlCode("CC_LATCH_ON", javadnp3JNI.CC_LATCH_ON_get());
  public final static ControlCode CC_LATCH_OFF = new ControlCode("CC_LATCH_OFF", javadnp3JNI.CC_LATCH_OFF_get());
  public final static ControlCode CC_PULSE_CLOSE = new ControlCode("CC_PULSE_CLOSE", javadnp3JNI.CC_PULSE_CLOSE_get());
  public final static ControlCode CC_PULSE_TRIP = new ControlCode("CC_PULSE_TRIP", javadnp3JNI.CC_PULSE_TRIP_get());
  public final static ControlCode CC_UNDEFINED = new ControlCode("CC_UNDEFINED", javadnp3JNI.CC_UNDEFINED_get());

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static ControlCode swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + ControlCode.class + " with value " + swigValue);
  }

  private ControlCode(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private ControlCode(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private ControlCode(String swigName, ControlCode swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static ControlCode[] swigValues = { CC_NULL, CC_PULSE, CC_LATCH_ON, CC_LATCH_OFF, CC_PULSE_CLOSE, CC_PULSE_TRIP, CC_UNDEFINED };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

