/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.petrasolar.nms.protocol.dnp3;

public final class CounterQuality {
  public final static CounterQuality CQ_ONLINE = new CounterQuality("CQ_ONLINE", javadnp3JNI.CQ_ONLINE_get());
  public final static CounterQuality CQ_RESTART = new CounterQuality("CQ_RESTART", javadnp3JNI.CQ_RESTART_get());
  public final static CounterQuality CQ_COMM_LOST = new CounterQuality("CQ_COMM_LOST", javadnp3JNI.CQ_COMM_LOST_get());
  public final static CounterQuality CQ_REMOTE_FORCED_DATA = new CounterQuality("CQ_REMOTE_FORCED_DATA", javadnp3JNI.CQ_REMOTE_FORCED_DATA_get());
  public final static CounterQuality CQ_LOCAL_FORCED_DATA = new CounterQuality("CQ_LOCAL_FORCED_DATA", javadnp3JNI.CQ_LOCAL_FORCED_DATA_get());
  public final static CounterQuality CQ_ROLLOVER = new CounterQuality("CQ_ROLLOVER", javadnp3JNI.CQ_ROLLOVER_get());
  public final static CounterQuality CQ_DISCONTINUITY = new CounterQuality("CQ_DISCONTINUITY", javadnp3JNI.CQ_DISCONTINUITY_get());
  public final static CounterQuality CQ_RESERVED = new CounterQuality("CQ_RESERVED", javadnp3JNI.CQ_RESERVED_get());

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static CounterQuality swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + CounterQuality.class + " with value " + swigValue);
  }

  private CounterQuality(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private CounterQuality(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private CounterQuality(String swigName, CounterQuality swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static CounterQuality[] swigValues = { CQ_ONLINE, CQ_RESTART, CQ_COMM_LOST, CQ_REMOTE_FORCED_DATA, CQ_LOCAL_FORCED_DATA, CQ_ROLLOVER, CQ_DISCONTINUITY, CQ_RESERVED };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

