/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.petrasolar.nms.protocol.dnp3;

public class Counter extends UnsignedPoint {
  private long swigCPtr;

  protected Counter(long cPtr, boolean cMemoryOwn) {
    super(javadnp3JNI.Counter_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Counter obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        javadnp3JNI.delete_Counter(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  protected void swigDirectorDisconnect() {
    swigCMemOwn = false;
    delete();
  }

  public void swigReleaseOwnership() {
    swigCMemOwn = false;
    javadnp3JNI.Counter_change_ownership(this, swigCPtr, false);
  }

  public void swigTakeOwnership() {
    swigCMemOwn = true;
    javadnp3JNI.Counter_change_ownership(this, swigCPtr, true);
  }

  public Counter() {
    this(javadnp3JNI.new_Counter__SWIG_0(), true);
    javadnp3JNI.Counter_director_connect(this, swigCPtr, swigCMemOwn, true);
  }

  public Counter(long aVal, short aQuality) {
    this(javadnp3JNI.new_Counter__SWIG_1(aVal, aQuality), true);
    javadnp3JNI.Counter_director_connect(this, swigCPtr, swigCMemOwn, true);
  }

  public Counter(long aVal) {
    this(javadnp3JNI.new_Counter__SWIG_2(aVal), true);
    javadnp3JNI.Counter_director_connect(this, swigCPtr, swigCMemOwn, true);
  }

  public short get_counter() {
    return javadnp3JNI.Counter_get_counter(swigCPtr, this);
  }

  public short set_counter(short aValue) {
    return javadnp3JNI.Counter_set_counter(swigCPtr, this, aValue);
  }

  public final static int ONLINE = javadnp3JNI.Counter_ONLINE_get();
  public final static DataTypes MeasEnum = DataTypes.swigToEnum(javadnp3JNI.Counter_MeasEnum_get());
}
