/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.petrasolar.nms.protocol.dnp3;

public class DeadbandPointRecord extends EventPointRecord {
  private long swigCPtr;

  protected DeadbandPointRecord(long cPtr, boolean cMemoryOwn) {
    super(javadnp3JNI.DeadbandPointRecord_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(DeadbandPointRecord obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        javadnp3JNI.delete_DeadbandPointRecord(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public DeadbandPointRecord(String arName, PointClass aPointClass, double aDeadband) {
    this(javadnp3JNI.new_DeadbandPointRecord__SWIG_0(arName, aPointClass.swigValue(), aDeadband), true);
  }

  public DeadbandPointRecord() {
    this(javadnp3JNI.new_DeadbandPointRecord__SWIG_1(), true);
  }

  public void setDeadband(double value) {
    javadnp3JNI.DeadbandPointRecord_Deadband_set(swigCPtr, this, value);
  }

  public double getDeadband() {
    return javadnp3JNI.DeadbandPointRecord_Deadband_get(swigCPtr, this);
  }

}
