/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.petrasolar.nms.protocol.dnp3;

public class DeviceTemplate {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected DeviceTemplate(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(DeviceTemplate obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        javadnp3JNI.delete_DeviceTemplate(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public DeviceTemplate(long aNumBinary, long aNumAnalog, long aNumCounter, long aNumControlStatus, long aNumSetpointStatus, long aNumControls, long aNumSetpoints) {
    this(javadnp3JNI.new_DeviceTemplate__SWIG_0(aNumBinary, aNumAnalog, aNumCounter, aNumControlStatus, aNumSetpointStatus, aNumControls, aNumSetpoints), true);
  }

  public DeviceTemplate(long aNumBinary, long aNumAnalog, long aNumCounter, long aNumControlStatus, long aNumSetpointStatus, long aNumControls) {
    this(javadnp3JNI.new_DeviceTemplate__SWIG_1(aNumBinary, aNumAnalog, aNumCounter, aNumControlStatus, aNumSetpointStatus, aNumControls), true);
  }

  public DeviceTemplate(long aNumBinary, long aNumAnalog, long aNumCounter, long aNumControlStatus, long aNumSetpointStatus) {
    this(javadnp3JNI.new_DeviceTemplate__SWIG_2(aNumBinary, aNumAnalog, aNumCounter, aNumControlStatus, aNumSetpointStatus), true);
  }

  public DeviceTemplate(long aNumBinary, long aNumAnalog, long aNumCounter, long aNumControlStatus) {
    this(javadnp3JNI.new_DeviceTemplate__SWIG_3(aNumBinary, aNumAnalog, aNumCounter, aNumControlStatus), true);
  }

  public DeviceTemplate(long aNumBinary, long aNumAnalog, long aNumCounter) {
    this(javadnp3JNI.new_DeviceTemplate__SWIG_4(aNumBinary, aNumAnalog, aNumCounter), true);
  }

  public DeviceTemplate(long aNumBinary, long aNumAnalog) {
    this(javadnp3JNI.new_DeviceTemplate__SWIG_5(aNumBinary, aNumAnalog), true);
  }

  public DeviceTemplate(long aNumBinary) {
    this(javadnp3JNI.new_DeviceTemplate__SWIG_6(aNumBinary), true);
  }

  public DeviceTemplate() {
    this(javadnp3JNI.new_DeviceTemplate__SWIG_7(), true);
  }

  public void setMBinary(VectorOfEventPointRecord value) {
    javadnp3JNI.DeviceTemplate_mBinary_set(swigCPtr, this, VectorOfEventPointRecord.getCPtr(value), value);
  }

  public VectorOfEventPointRecord getMBinary() {
    long cPtr = javadnp3JNI.DeviceTemplate_mBinary_get(swigCPtr, this);
    return (cPtr == 0) ? null : new VectorOfEventPointRecord(cPtr, false);
  }

  public void setMCounter(VectorOfEventPointRecord value) {
    javadnp3JNI.DeviceTemplate_mCounter_set(swigCPtr, this, VectorOfEventPointRecord.getCPtr(value), value);
  }

  public VectorOfEventPointRecord getMCounter() {
    long cPtr = javadnp3JNI.DeviceTemplate_mCounter_get(swigCPtr, this);
    return (cPtr == 0) ? null : new VectorOfEventPointRecord(cPtr, false);
  }

  public void setMAnalog(VectorOfDeadbandPointRecord value) {
    javadnp3JNI.DeviceTemplate_mAnalog_set(swigCPtr, this, VectorOfDeadbandPointRecord.getCPtr(value), value);
  }

  public VectorOfDeadbandPointRecord getMAnalog() {
    long cPtr = javadnp3JNI.DeviceTemplate_mAnalog_get(swigCPtr, this);
    return (cPtr == 0) ? null : new VectorOfDeadbandPointRecord(cPtr, false);
  }

  public void setMControlStatus(VectorOfPointRecord value) {
    javadnp3JNI.DeviceTemplate_mControlStatus_set(swigCPtr, this, VectorOfPointRecord.getCPtr(value), value);
  }

  public VectorOfPointRecord getMControlStatus() {
    long cPtr = javadnp3JNI.DeviceTemplate_mControlStatus_get(swigCPtr, this);
    return (cPtr == 0) ? null : new VectorOfPointRecord(cPtr, false);
  }

  public void setMSetpointStatus(VectorOfPointRecord value) {
    javadnp3JNI.DeviceTemplate_mSetpointStatus_set(swigCPtr, this, VectorOfPointRecord.getCPtr(value), value);
  }

  public VectorOfPointRecord getMSetpointStatus() {
    long cPtr = javadnp3JNI.DeviceTemplate_mSetpointStatus_get(swigCPtr, this);
    return (cPtr == 0) ? null : new VectorOfPointRecord(cPtr, false);
  }

  public void setMControls(VectorOfControlRecord value) {
    javadnp3JNI.DeviceTemplate_mControls_set(swigCPtr, this, VectorOfControlRecord.getCPtr(value), value);
  }

  public VectorOfControlRecord getMControls() {
    long cPtr = javadnp3JNI.DeviceTemplate_mControls_get(swigCPtr, this);
    return (cPtr == 0) ? null : new VectorOfControlRecord(cPtr, false);
  }

  public void setMSetpoints(VectorOfControlRecord value) {
    javadnp3JNI.DeviceTemplate_mSetpoints_set(swigCPtr, this, VectorOfControlRecord.getCPtr(value), value);
  }

  public VectorOfControlRecord getMSetpoints() {
    long cPtr = javadnp3JNI.DeviceTemplate_mSetpoints_get(swigCPtr, this);
    return (cPtr == 0) ? null : new VectorOfControlRecord(cPtr, false);
  }

  public void setMStartOnline(boolean value) {
    javadnp3JNI.DeviceTemplate_mStartOnline_set(swigCPtr, this, value);
  }

  public boolean getMStartOnline() {
    return javadnp3JNI.DeviceTemplate_mStartOnline_get(swigCPtr, this);
  }

  public void Publish(IDataObserver arg0) {
    javadnp3JNI.DeviceTemplate_Publish(swigCPtr, this, IDataObserver.getCPtr(arg0), arg0);
  }

}
