/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.petrasolar.nms.protocol.dnp3;

public class DoublePoint extends DataPoint {
  private long swigCPtr;

  protected DoublePoint(long cPtr, boolean cMemoryOwn) {
    super(javadnp3JNI.DoublePoint_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(DoublePoint obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        javadnp3JNI.delete_DoublePoint(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  protected void swigDirectorDisconnect() {
    swigCMemOwn = false;
    delete();
  }

  public void swigReleaseOwnership() {
    swigCMemOwn = false;
    javadnp3JNI.DoublePoint_change_ownership(this, swigCPtr, false);
  }

  public void swigTakeOwnership() {
    swigCMemOwn = true;
    javadnp3JNI.DoublePoint_change_ownership(this, swigCPtr, true);
  }

  public double GetValue() {
    return javadnp3JNI.DoublePoint_GetValue(swigCPtr, this);
  }

  public void SetValue(double aValue) {
    javadnp3JNI.DoublePoint_SetValue(swigCPtr, this, aValue);
  }

  public boolean ShouldGenerateEvent(DoublePoint arRHS, double aDeadband, double aLastReportedVal) {
    return javadnp3JNI.DoublePoint_ShouldGenerateEvent(swigCPtr, this, DoublePoint.getCPtr(arRHS), arRHS, aDeadband, aLastReportedVal);
  }

  public static double getMAX_VALUE() {
    return javadnp3JNI.DoublePoint_MAX_VALUE_get();
  }

  public static double getMIN_VALUE() {
    return javadnp3JNI.DoublePoint_MIN_VALUE_get();
  }

  public String ToString() {
    return (getClass() == DoublePoint.class) ? javadnp3JNI.DoublePoint_ToString(swigCPtr, this) : javadnp3JNI.DoublePoint_ToStringSwigExplicitDoublePoint(swigCPtr, this);
  }

  public boolean tdpEqual(DoublePoint rhs) {
    return javadnp3JNI.DoublePoint_tdpEqual(swigCPtr, this, DoublePoint.getCPtr(rhs), rhs);
  }

  protected DoublePoint(short aQuality, DataTypes aType) {
    this(javadnp3JNI.new_DoublePoint(aQuality, aType.swigValue()), true);
    javadnp3JNI.DoublePoint_director_connect(this, swigCPtr, swigCMemOwn, true);
  }

}
