/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.petrasolar.nms.protocol.dnp3;

public class EventMaxConfig {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected EventMaxConfig(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(EventMaxConfig obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        javadnp3JNI.delete_EventMaxConfig(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public EventMaxConfig() {
    this(javadnp3JNI.new_EventMaxConfig__SWIG_0(), true);
  }

  public EventMaxConfig(long arg0, long arg1, long arg2, long arg3) {
    this(javadnp3JNI.new_EventMaxConfig__SWIG_1(arg0, arg1, arg2, arg3), true);
  }

  public void setMMaxBinaryEvents(long value) {
    javadnp3JNI.EventMaxConfig_mMaxBinaryEvents_set(swigCPtr, this, value);
  }

  public long getMMaxBinaryEvents() {
    return javadnp3JNI.EventMaxConfig_mMaxBinaryEvents_get(swigCPtr, this);
  }

  public void setMMaxAnalogEvents(long value) {
    javadnp3JNI.EventMaxConfig_mMaxAnalogEvents_set(swigCPtr, this, value);
  }

  public long getMMaxAnalogEvents() {
    return javadnp3JNI.EventMaxConfig_mMaxAnalogEvents_get(swigCPtr, this);
  }

  public void setMMaxCounterEvents(long value) {
    javadnp3JNI.EventMaxConfig_mMaxCounterEvents_set(swigCPtr, this, value);
  }

  public long getMMaxCounterEvents() {
    return javadnp3JNI.EventMaxConfig_mMaxCounterEvents_get(swigCPtr, this);
  }

  public void setMMaxVtoEvents(long value) {
    javadnp3JNI.EventMaxConfig_mMaxVtoEvents_set(swigCPtr, this, value);
  }

  public long getMMaxVtoEvents() {
    return javadnp3JNI.EventMaxConfig_mMaxVtoEvents_get(swigCPtr, this);
  }

}
