/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.petrasolar.nms.protocol.dnp3;

public class ExceptionScan {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected ExceptionScan(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ExceptionScan obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        javadnp3JNI.delete_ExceptionScan(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setClassMask(int value) {
    javadnp3JNI.ExceptionScan_ClassMask_set(swigCPtr, this, value);
  }

  public int getClassMask() {
    return javadnp3JNI.ExceptionScan_ClassMask_get(swigCPtr, this);
  }

  public void setScanRate(long value) {
    javadnp3JNI.ExceptionScan_ScanRate_set(swigCPtr, this, value);
  }

  public long getScanRate() {
    return javadnp3JNI.ExceptionScan_ScanRate_get(swigCPtr, this);
  }

  public ExceptionScan() {
    this(javadnp3JNI.new_ExceptionScan(), true);
  }

}
