/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.petrasolar.nms.protocol.dnp3;

public class FilterAssoc {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected FilterAssoc(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(FilterAssoc obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        javadnp3JNI.delete_FilterAssoc(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setLev(FilterLevel value) {
    javadnp3JNI.FilterAssoc_lev_set(swigCPtr, this, value.swigValue());
  }

  public FilterLevel getLev() {
    return FilterLevel.swigToEnum(javadnp3JNI.FilterAssoc_lev_get(swigCPtr, this));
  }

  public void setId(char value) {
    javadnp3JNI.FilterAssoc_id_set(swigCPtr, this, value);
  }

  public char getId() {
    return javadnp3JNI.FilterAssoc_id_get(swigCPtr, this);
  }

  public FilterAssoc() {
    this(javadnp3JNI.new_FilterAssoc(), true);
  }

}
