/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.petrasolar.nms.protocol.dnp3;

public final class FilterLevel {
  public final static FilterLevel LEV_EVENT = new FilterLevel("LEV_EVENT", javadnp3JNI.LEV_EVENT_get());
  public final static FilterLevel LEV_ERROR = new FilterLevel("LEV_ERROR", javadnp3JNI.LEV_ERROR_get());
  public final static FilterLevel LEV_WARNING = new FilterLevel("LEV_WARNING", javadnp3JNI.LEV_WARNING_get());
  public final static FilterLevel LEV_INFO = new FilterLevel("LEV_INFO", javadnp3JNI.LEV_INFO_get());
  public final static FilterLevel LEV_INTERPRET = new FilterLevel("LEV_INTERPRET", javadnp3JNI.LEV_INTERPRET_get());
  public final static FilterLevel LEV_COMM = new FilterLevel("LEV_COMM", javadnp3JNI.LEV_COMM_get());
  public final static FilterLevel LEV_DEBUG = new FilterLevel("LEV_DEBUG", javadnp3JNI.LEV_DEBUG_get());

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static FilterLevel swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + FilterLevel.class + " with value " + swigValue);
  }

  private FilterLevel(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private FilterLevel(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private FilterLevel(String swigName, FilterLevel swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static FilterLevel[] swigValues = { LEV_EVENT, LEV_ERROR, LEV_WARNING, LEV_INFO, LEV_INTERPRET, LEV_COMM, LEV_DEBUG };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

