/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.petrasolar.nms.protocol.dnp3;

public class FixedCommandHandler extends ICommandHandler {
  private long swigCPtr;

  protected FixedCommandHandler(long cPtr, boolean cMemoryOwn) {
    super(javadnp3JNI.FixedCommandHandler_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(FixedCommandHandler obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        javadnp3JNI.delete_FixedCommandHandler(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  protected void swigDirectorDisconnect() {
    swigCMemOwn = false;
    delete();
  }

  public void swigReleaseOwnership() {
    swigCMemOwn = false;
    javadnp3JNI.FixedCommandHandler_change_ownership(this, swigCPtr, false);
  }

  public void swigTakeOwnership() {
    swigCMemOwn = true;
    javadnp3JNI.FixedCommandHandler_change_ownership(this, swigCPtr, true);
  }

  public FixedCommandHandler(CommandStatus aStatus) {
    this(javadnp3JNI.new_FixedCommandHandler(aStatus.swigValue()), true);
    javadnp3JNI.FixedCommandHandler_director_connect(this, swigCPtr, swigCMemOwn, true);
  }

  public CommandStatus HandleControl(BinaryOutput arg0, long arg1) {
    return CommandStatus.swigToEnum((getClass() == FixedCommandHandler.class) ? javadnp3JNI.FixedCommandHandler_HandleControl__SWIG_0(swigCPtr, this, BinaryOutput.getCPtr(arg0), arg0, arg1) : javadnp3JNI.FixedCommandHandler_HandleControlSwigExplicitFixedCommandHandler__SWIG_0(swigCPtr, this, BinaryOutput.getCPtr(arg0), arg0, arg1));
  }

  public CommandStatus HandleControl(Setpoint arg0, long arg1) {
    return CommandStatus.swigToEnum((getClass() == FixedCommandHandler.class) ? javadnp3JNI.FixedCommandHandler_HandleControl__SWIG_1(swigCPtr, this, Setpoint.getCPtr(arg0), arg0, arg1) : javadnp3JNI.FixedCommandHandler_HandleControlSwigExplicitFixedCommandHandler__SWIG_1(swigCPtr, this, Setpoint.getCPtr(arg0), arg0, arg1));
  }

  public void setMStatus(CommandStatus value) {
    javadnp3JNI.FixedCommandHandler_mStatus_set(swigCPtr, this, value.swigValue());
  }

  public CommandStatus getMStatus() {
    return CommandStatus.swigToEnum(javadnp3JNI.FixedCommandHandler_mStatus_get(swigCPtr, this));
  }

}
