/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.petrasolar.nms.protocol.dnp3;

public final class FlowType {
  public final static FlowType FLOW_NONE = new FlowType("FLOW_NONE");
  public final static FlowType FLOW_HARDWARE = new FlowType("FLOW_HARDWARE");
  public final static FlowType FLOW_XONXOFF = new FlowType("FLOW_XONXOFF");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static FlowType swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + FlowType.class + " with value " + swigValue);
  }

  private FlowType(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private FlowType(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private FlowType(String swigName, FlowType swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static FlowType[] swigValues = { FLOW_NONE, FLOW_HARDWARE, FLOW_XONXOFF };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

