/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.petrasolar.nms.protocol.dnp3;

public class GrpVar {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected GrpVar(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(GrpVar obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        javadnp3JNI.delete_GrpVar(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public GrpVar() {
    this(javadnp3JNI.new_GrpVar__SWIG_0(), true);
  }

  public GrpVar(int aGrp, int aVar) {
    this(javadnp3JNI.new_GrpVar__SWIG_1(aGrp, aVar), true);
  }

  public void setGrp(int value) {
    javadnp3JNI.GrpVar_Grp_set(swigCPtr, this, value);
  }

  public int getGrp() {
    return javadnp3JNI.GrpVar_Grp_get(swigCPtr, this);
  }

  public void setVar(int value) {
    javadnp3JNI.GrpVar_Var_set(swigCPtr, this, value);
  }

  public int getVar() {
    return javadnp3JNI.GrpVar_Var_get(swigCPtr, this);
  }

}
