/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.petrasolar.nms.protocol.dnp3;

public class ICommandSource {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected ICommandSource(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ICommandSource obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        javadnp3JNI.delete_ICommandSource(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  protected void swigDirectorDisconnect() {
    swigCMemOwn = false;
    delete();
  }

  public void swigReleaseOwnership() {
    swigCMemOwn = false;
    javadnp3JNI.ICommandSource_change_ownership(this, swigCPtr, false);
  }

  public void swigTakeOwnership() {
    swigCMemOwn = true;
    javadnp3JNI.ICommandSource_change_ownership(this, swigCPtr, true);
  }

  public void SetNotifier(INotifier apNotifier) {
    javadnp3JNI.ICommandSource_SetNotifier(swigCPtr, this, INotifier.getCPtr(apNotifier), apNotifier);
  }

  public boolean ExecuteCommand(ICommandHandler apHandler) {
    return javadnp3JNI.ICommandSource_ExecuteCommand(swigCPtr, this, ICommandHandler.getCPtr(apHandler), apHandler);
  }

  public ICommandSource() {
    this(javadnp3JNI.new_ICommandSource(), true);
    javadnp3JNI.ICommandSource_director_connect(this, swigCPtr, swigCMemOwn, true);
  }

}
