/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.petrasolar.nms.protocol.dnp3;

public class ICommandHandler {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected ICommandHandler(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ICommandHandler obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        javadnp3JNI.delete_ICommandHandler(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  protected void swigDirectorDisconnect() {
    swigCMemOwn = false;
    delete();
  }

  public void swigReleaseOwnership() {
    swigCMemOwn = false;
    javadnp3JNI.ICommandHandler_change_ownership(this, swigCPtr, false);
  }

  public void swigTakeOwnership() {
    swigCMemOwn = true;
    javadnp3JNI.ICommandHandler_change_ownership(this, swigCPtr, true);
  }

  public CommandStatus HandleControl(BinaryOutput aControl, long aIndex) {
    return CommandStatus.swigToEnum(javadnp3JNI.ICommandHandler_HandleControl__SWIG_0(swigCPtr, this, BinaryOutput.getCPtr(aControl), aControl, aIndex));
  }

  public CommandStatus HandleControl(Setpoint aControl, long aIndex) {
    return CommandStatus.swigToEnum(javadnp3JNI.ICommandHandler_HandleControl__SWIG_1(swigCPtr, this, Setpoint.getCPtr(aControl), aControl, aIndex));
  }

  public ICommandHandler() {
    this(javadnp3JNI.new_ICommandHandler(), true);
    javadnp3JNI.ICommandHandler_director_connect(this, swigCPtr, swigCMemOwn, true);
  }

}
