/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.petrasolar.nms.protocol.dnp3;

public class IStackObserver {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected IStackObserver(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(IStackObserver obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        javadnp3JNI.delete_IStackObserver(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  protected void swigDirectorDisconnect() {
    swigCMemOwn = false;
    delete();
  }

  public void swigReleaseOwnership() {
    swigCMemOwn = false;
    javadnp3JNI.IStackObserver_change_ownership(this, swigCPtr, false);
  }

  public void swigTakeOwnership() {
    swigCMemOwn = true;
    javadnp3JNI.IStackObserver_change_ownership(this, swigCPtr, true);
  }

  public void OnStateChange(StackStates aState) {
    javadnp3JNI.IStackObserver_OnStateChange(swigCPtr, this, aState.swigValue());
  }

  public IStackObserver() {
    this(javadnp3JNI.new_IStackObserver(), true);
    javadnp3JNI.IStackObserver_director_connect(this, swigCPtr, swigCMemOwn, true);
  }

}
