/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.petrasolar.nms.protocol.dnp3;

public class ITransactable {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected ITransactable(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ITransactable obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        javadnp3JNI.delete_ITransactable(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  protected void swigDirectorDisconnect() {
    swigCMemOwn = false;
    delete();
  }

  public void swigReleaseOwnership() {
    swigCMemOwn = false;
    javadnp3JNI.ITransactable_change_ownership(this, swigCPtr, false);
  }

  public void swigTakeOwnership() {
    swigCMemOwn = true;
    javadnp3JNI.ITransactable_change_ownership(this, swigCPtr, true);
  }

  public ITransactable() {
    this(javadnp3JNI.new_ITransactable(), true);
    javadnp3JNI.ITransactable_director_connect(this, swigCPtr, swigCMemOwn, true);
  }

  public void Start() {
    javadnp3JNI.ITransactable_Start(swigCPtr, this);
  }

  public void End() {
    javadnp3JNI.ITransactable_End(swigCPtr, this);
  }

  protected void _Start() {
    javadnp3JNI.ITransactable__Start(swigCPtr, this);
  }

  protected void _End() {
    javadnp3JNI.ITransactable__End(swigCPtr, this);
  }

}
