/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.petrasolar.nms.protocol.dnp3;

public class javadnp3 implements javadnp3Constants {
  public static String ConvertPhysicalLayerStateToString(PhysicalLayerState aState) {
    return javadnp3JNI.ConvertPhysicalLayerStateToString(aState.swigValue());
  }

  public static SWIGTYPE_p_std__ostream PhysLayerStateToString(SWIGTYPE_p_std__ostream output, PhysicalLayerState aState) {
    return new SWIGTYPE_p_std__ostream(javadnp3JNI.PhysLayerStateToString(SWIGTYPE_p_std__ostream.getCPtr(output), aState.swigValue()), false);
  }

  public static CommandStatus ByteToCommandStatus(short aField) {
    return CommandStatus.swigToEnum(javadnp3JNI.ByteToCommandStatus(aField));
  }

  public static String ToString(CommandStatus aType) {
    return javadnp3JNI.ToString__SWIG_0(aType.swigValue());
  }

  public static ControlCode ByteToControlCode(short aField) {
    return ControlCode.swigToEnum(javadnp3JNI.ByteToControlCode(aField));
  }

  public static String ToString(ControlCode aType) {
    return javadnp3JNI.ToString__SWIG_1(aType.swigValue());
  }

  public static String ToString(CommandTypes aType) {
    return javadnp3JNI.ToString__SWIG_2(aType.swigValue());
  }

  public static String GetDataTypeName(DataTypes aType) {
    return javadnp3JNI.GetDataTypeName(aType.swigValue());
  }

  public static PointClass IntToPointClass(int aClass) {
    return PointClass.swigToEnum(javadnp3JNI.IntToPointClass(aClass));
  }

  public static String ConvertStackStateToString(StackStates aState) {
    return javadnp3JNI.ConvertStackStateToString(aState.swigValue());
  }

}
