/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.petrasolar.nms.protocol.dnp3;

public class LogEntry {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected LogEntry(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(LogEntry obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        javadnp3JNI.delete_LogEntry(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public LogEntry() {
    this(javadnp3JNI.new_LogEntry__SWIG_0(), true);
  }

  public LogEntry(FilterLevel aLevel, String aDeviceName, String aLocation, String aMessage, int aErrorCode) {
    this(javadnp3JNI.new_LogEntry__SWIG_1(aLevel.swigValue(), aDeviceName, aLocation, aMessage, aErrorCode), true);
  }

  public String GetDeviceName() {
    return javadnp3JNI.LogEntry_GetDeviceName(swigCPtr, this);
  }

  public String GetLocation() {
    return javadnp3JNI.LogEntry_GetLocation(swigCPtr, this);
  }

  public String GetMessage() {
    return javadnp3JNI.LogEntry_GetMessage(swigCPtr, this);
  }

  public FilterLevel GetFilterLevel() {
    return FilterLevel.swigToEnum(javadnp3JNI.LogEntry_GetFilterLevel(swigCPtr, this));
  }

  public String GetTimeString() {
    return javadnp3JNI.LogEntry_GetTimeString(swigCPtr, this);
  }

  public long GetTimeStamp() {
    return javadnp3JNI.LogEntry_GetTimeStamp(swigCPtr, this);
  }

  public int GetErrorCode() {
    return javadnp3JNI.LogEntry_GetErrorCode(swigCPtr, this);
  }

  public String LogString(boolean aUseLocation) {
    return javadnp3JNI.LogEntry_LogString__SWIG_0(swigCPtr, this, aUseLocation);
  }

  public String LogString() {
    return javadnp3JNI.LogEntry_LogString__SWIG_1(swigCPtr, this);
  }

  public boolean GetValue(String arKey, SWIGTYPE_p_std__string arValue) {
    return javadnp3JNI.LogEntry_GetValue__SWIG_0(swigCPtr, this, arKey, SWIGTYPE_p_std__string.getCPtr(arValue));
  }

  public boolean GetValue(String arKey, SWIGTYPE_p_int arValue) {
    return javadnp3JNI.LogEntry_GetValue__SWIG_1(swigCPtr, this, arKey, SWIGTYPE_p_int.getCPtr(arValue));
  }

  public boolean GetValue(String arKey, SWIGTYPE_p_boost__int64_t arValue) {
    return javadnp3JNI.LogEntry_GetValue__SWIG_2(swigCPtr, this, arKey, SWIGTYPE_p_boost__int64_t.getCPtr(arValue));
  }

  public void AddValue(String arKey, String arValue) {
    javadnp3JNI.LogEntry_AddValue__SWIG_0(swigCPtr, this, arKey, arValue);
  }

  public void AddValue(String arKey, int aValue) {
    javadnp3JNI.LogEntry_AddValue__SWIG_1(swigCPtr, this, arKey, aValue);
  }

  public void AddValue(String arKey, long aValue) {
    javadnp3JNI.LogEntry_AddValue__SWIG_2(swigCPtr, this, arKey, aValue);
  }

}
