/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.petrasolar.nms.protocol.dnp3;

public class MasterStackConfig {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected MasterStackConfig(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(MasterStackConfig obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        javadnp3JNI.delete_MasterStackConfig(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public MasterStackConfig() {
    this(javadnp3JNI.new_MasterStackConfig(), true);
  }

  public void setMaster(MasterConfig value) {
    javadnp3JNI.MasterStackConfig_master_set(swigCPtr, this, MasterConfig.getCPtr(value), value);
  }

  public MasterConfig getMaster() {
    long cPtr = javadnp3JNI.MasterStackConfig_master_get(swigCPtr, this);
    return (cPtr == 0) ? null : new MasterConfig(cPtr, false);
  }

  public void setApp(AppConfig value) {
    javadnp3JNI.MasterStackConfig_app_set(swigCPtr, this, AppConfig.getCPtr(value), value);
  }

  public AppConfig getApp() {
    long cPtr = javadnp3JNI.MasterStackConfig_app_get(swigCPtr, this);
    return (cPtr == 0) ? null : new AppConfig(cPtr, false);
  }

  public void setLink(LinkConfig value) {
    javadnp3JNI.MasterStackConfig_link_set(swigCPtr, this, LinkConfig.getCPtr(value), value);
  }

  public LinkConfig getLink() {
    long cPtr = javadnp3JNI.MasterStackConfig_link_get(swigCPtr, this);
    return (cPtr == 0) ? null : new LinkConfig(cPtr, false);
  }

  public void setVto(VtoConfig value) {
    javadnp3JNI.MasterStackConfig_vto_set(swigCPtr, this, VtoConfig.getCPtr(value), value);
  }

  public VtoConfig getVto() {
    long cPtr = javadnp3JNI.MasterStackConfig_vto_get(swigCPtr, this);
    return (cPtr == 0) ? null : new VtoConfig(cPtr, false);
  }

}
