/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.petrasolar.nms.protocol.dnp3;

public final class ParityType {
  public final static ParityType PAR_NONE = new ParityType("PAR_NONE");
  public final static ParityType PAR_EVEN = new ParityType("PAR_EVEN");
  public final static ParityType PAR_ODD = new ParityType("PAR_ODD");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static ParityType swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + ParityType.class + " with value " + swigValue);
  }

  private ParityType(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private ParityType(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private ParityType(String swigName, ParityType swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static ParityType[] swigValues = { PAR_NONE, PAR_EVEN, PAR_ODD };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

