/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.petrasolar.nms.protocol.dnp3;

public class PhysLayerSettings {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected PhysLayerSettings(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(PhysLayerSettings obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        javadnp3JNI.delete_PhysLayerSettings(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public PhysLayerSettings() {
    this(javadnp3JNI.new_PhysLayerSettings__SWIG_0(), true);
  }

  public PhysLayerSettings(FilterLevel aLevel, long aRetryTimeout, IPhysicalLayerObserver apObserver) {
    this(javadnp3JNI.new_PhysLayerSettings__SWIG_1(aLevel.swigValue(), aRetryTimeout, IPhysicalLayerObserver.getCPtr(apObserver), apObserver), true);
  }

  public PhysLayerSettings(FilterLevel aLevel, long aRetryTimeout) {
    this(javadnp3JNI.new_PhysLayerSettings__SWIG_2(aLevel.swigValue(), aRetryTimeout), true);
  }

  public void setLogLevel(FilterLevel value) {
    javadnp3JNI.PhysLayerSettings_LogLevel_set(swigCPtr, this, value.swigValue());
  }

  public FilterLevel getLogLevel() {
    return FilterLevel.swigToEnum(javadnp3JNI.PhysLayerSettings_LogLevel_get(swigCPtr, this));
  }

  public void setRetryTimeout(long value) {
    javadnp3JNI.PhysLayerSettings_RetryTimeout_set(swigCPtr, this, value);
  }

  public long getRetryTimeout() {
    return javadnp3JNI.PhysLayerSettings_RetryTimeout_get(swigCPtr, this);
  }

  public void setMpObserver(IPhysicalLayerObserver value) {
    javadnp3JNI.PhysLayerSettings_mpObserver_set(swigCPtr, this, IPhysicalLayerObserver.getCPtr(value), value);
  }

  public IPhysicalLayerObserver getMpObserver() {
    long cPtr = javadnp3JNI.PhysLayerSettings_mpObserver_get(swigCPtr, this);
    return (cPtr == 0) ? null : new IPhysicalLayerObserver(cPtr, false);
  }

}
