/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.petrasolar.nms.protocol.dnp3;

public final class PhysicalLayerState {
  public final static PhysicalLayerState PLS_CLOSED = new PhysicalLayerState("PLS_CLOSED");
  public final static PhysicalLayerState PLS_OPENING = new PhysicalLayerState("PLS_OPENING");
  public final static PhysicalLayerState PLS_WAITING = new PhysicalLayerState("PLS_WAITING");
  public final static PhysicalLayerState PLS_OPEN = new PhysicalLayerState("PLS_OPEN");
  public final static PhysicalLayerState PLS_SHUTDOWN = new PhysicalLayerState("PLS_SHUTDOWN");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static PhysicalLayerState swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + PhysicalLayerState.class + " with value " + swigValue);
  }

  private PhysicalLayerState(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private PhysicalLayerState(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private PhysicalLayerState(String swigName, PhysicalLayerState swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static PhysicalLayerState[] swigValues = { PLS_CLOSED, PLS_OPENING, PLS_WAITING, PLS_OPEN, PLS_SHUTDOWN };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

