/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.petrasolar.nms.protocol.dnp3;

public final class PointClass {
  public final static PointClass PC_CLASS_0 = new PointClass("PC_CLASS_0", javadnp3JNI.PC_CLASS_0_get());
  public final static PointClass PC_CLASS_1 = new PointClass("PC_CLASS_1", javadnp3JNI.PC_CLASS_1_get());
  public final static PointClass PC_CLASS_2 = new PointClass("PC_CLASS_2", javadnp3JNI.PC_CLASS_2_get());
  public final static PointClass PC_CLASS_3 = new PointClass("PC_CLASS_3", javadnp3JNI.PC_CLASS_3_get());
  public final static PointClass PC_ALL_EVENTS = new PointClass("PC_ALL_EVENTS", javadnp3JNI.PC_ALL_EVENTS_get());
  public final static PointClass PC_INVALID = new PointClass("PC_INVALID", javadnp3JNI.PC_INVALID_get());

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static PointClass swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + PointClass.class + " with value " + swigValue);
  }

  private PointClass(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private PointClass(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private PointClass(String swigName, PointClass swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static PointClass[] swigValues = { PC_CLASS_0, PC_CLASS_1, PC_CLASS_2, PC_CLASS_3, PC_ALL_EVENTS, PC_INVALID };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

