/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.petrasolar.nms.protocol.dnp3;

public final class SetpointQuality {
  public final static SetpointQuality PQ_ONLINE = new SetpointQuality("PQ_ONLINE", javadnp3JNI.PQ_ONLINE_get());
  public final static SetpointQuality PQ_RESTART = new SetpointQuality("PQ_RESTART", javadnp3JNI.PQ_RESTART_get());
  public final static SetpointQuality PQ_COMM_LOST = new SetpointQuality("PQ_COMM_LOST", javadnp3JNI.PQ_COMM_LOST_get());
  public final static SetpointQuality PQ_REMOTE_FORCED_DATA = new SetpointQuality("PQ_REMOTE_FORCED_DATA", javadnp3JNI.PQ_REMOTE_FORCED_DATA_get());
  public final static SetpointQuality PQ_RESERVED_1 = new SetpointQuality("PQ_RESERVED_1", javadnp3JNI.PQ_RESERVED_1_get());
  public final static SetpointQuality PQ_RESERVED_2 = new SetpointQuality("PQ_RESERVED_2", javadnp3JNI.PQ_RESERVED_2_get());
  public final static SetpointQuality PQ_RESERVED_3 = new SetpointQuality("PQ_RESERVED_3", javadnp3JNI.PQ_RESERVED_3_get());
  public final static SetpointQuality PQ_RESERVED_4 = new SetpointQuality("PQ_RESERVED_4", javadnp3JNI.PQ_RESERVED_4_get());

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static SetpointQuality swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + SetpointQuality.class + " with value " + swigValue);
  }

  private SetpointQuality(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private SetpointQuality(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private SetpointQuality(String swigName, SetpointQuality swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static SetpointQuality[] swigValues = { PQ_ONLINE, PQ_RESTART, PQ_COMM_LOST, PQ_REMOTE_FORCED_DATA, PQ_RESERVED_1, PQ_RESERVED_2, PQ_RESERVED_3, PQ_RESERVED_4 };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

