/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.petrasolar.nms.protocol.dnp3;

public class SetpointStatus extends DoublePoint {
  private long swigCPtr;

  protected SetpointStatus(long cPtr, boolean cMemoryOwn) {
    super(javadnp3JNI.SetpointStatus_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(SetpointStatus obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        javadnp3JNI.delete_SetpointStatus(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  protected void swigDirectorDisconnect() {
    swigCMemOwn = false;
    delete();
  }

  public void swigReleaseOwnership() {
    swigCMemOwn = false;
    javadnp3JNI.SetpointStatus_change_ownership(this, swigCPtr, false);
  }

  public void swigTakeOwnership() {
    swigCMemOwn = true;
    javadnp3JNI.SetpointStatus_change_ownership(this, swigCPtr, true);
  }

  public SetpointStatus() {
    this(javadnp3JNI.new_SetpointStatus__SWIG_0(), true);
    javadnp3JNI.SetpointStatus_director_connect(this, swigCPtr, swigCMemOwn, true);
  }

  public SetpointStatus(double aVal, short aQuality) {
    this(javadnp3JNI.new_SetpointStatus__SWIG_1(aVal, aQuality), true);
    javadnp3JNI.SetpointStatus_director_connect(this, swigCPtr, swigCMemOwn, true);
  }

  public SetpointStatus(double aVal) {
    this(javadnp3JNI.new_SetpointStatus__SWIG_2(aVal), true);
    javadnp3JNI.SetpointStatus_director_connect(this, swigCPtr, swigCMemOwn, true);
  }

  public double get_setpointstatus() {
    return javadnp3JNI.SetpointStatus_get_setpointstatus(swigCPtr, this);
  }

  public double set_setpointstatus(double aValue) {
    return javadnp3JNI.SetpointStatus_set_setpointstatus(swigCPtr, this, aValue);
  }

  public final static int ONLINE = javadnp3JNI.SetpointStatus_ONLINE_get();
  public final static DataTypes MeasEnum = DataTypes.swigToEnum(javadnp3JNI.SetpointStatus_MeasEnum_get());
}
