/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.petrasolar.nms.protocol.dnp3;

public final class SetpointEncodingType {
  public final static SetpointEncodingType SPET_INT16 = new SetpointEncodingType("SPET_INT16");
  public final static SetpointEncodingType SPET_INT32 = new SetpointEncodingType("SPET_INT32");
  public final static SetpointEncodingType SPET_FLOAT = new SetpointEncodingType("SPET_FLOAT");
  public final static SetpointEncodingType SPET_DOUBLE = new SetpointEncodingType("SPET_DOUBLE");
  public final static SetpointEncodingType SPET_AUTO_INT = new SetpointEncodingType("SPET_AUTO_INT");
  public final static SetpointEncodingType SPET_AUTO_DOUBLE = new SetpointEncodingType("SPET_AUTO_DOUBLE");
  public final static SetpointEncodingType SPET_UNSET = new SetpointEncodingType("SPET_UNSET");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static SetpointEncodingType swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + SetpointEncodingType.class + " with value " + swigValue);
  }

  private SetpointEncodingType(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private SetpointEncodingType(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private SetpointEncodingType(String swigName, SetpointEncodingType swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static SetpointEncodingType[] swigValues = { SPET_INT16, SPET_INT32, SPET_FLOAT, SPET_DOUBLE, SPET_AUTO_INT, SPET_AUTO_DOUBLE, SPET_UNSET };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

