/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.petrasolar.nms.protocol.dnp3;

public class SlaveStackConfig {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected SlaveStackConfig(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(SlaveStackConfig obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        javadnp3JNI.delete_SlaveStackConfig(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public SlaveStackConfig() {
    this(javadnp3JNI.new_SlaveStackConfig(), true);
  }

  public void setSlave(SlaveConfig value) {
    javadnp3JNI.SlaveStackConfig_slave_set(swigCPtr, this, SlaveConfig.getCPtr(value), value);
  }

  public SlaveConfig getSlave() {
    long cPtr = javadnp3JNI.SlaveStackConfig_slave_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SlaveConfig(cPtr, false);
  }

  public void setDevice(DeviceTemplate value) {
    javadnp3JNI.SlaveStackConfig_device_set(swigCPtr, this, DeviceTemplate.getCPtr(value), value);
  }

  public DeviceTemplate getDevice() {
    long cPtr = javadnp3JNI.SlaveStackConfig_device_get(swigCPtr, this);
    return (cPtr == 0) ? null : new DeviceTemplate(cPtr, false);
  }

  public void setApp(AppConfig value) {
    javadnp3JNI.SlaveStackConfig_app_set(swigCPtr, this, AppConfig.getCPtr(value), value);
  }

  public AppConfig getApp() {
    long cPtr = javadnp3JNI.SlaveStackConfig_app_get(swigCPtr, this);
    return (cPtr == 0) ? null : new AppConfig(cPtr, false);
  }

  public void setLink(LinkConfig value) {
    javadnp3JNI.SlaveStackConfig_link_set(swigCPtr, this, LinkConfig.getCPtr(value), value);
  }

  public LinkConfig getLink() {
    long cPtr = javadnp3JNI.SlaveStackConfig_link_get(swigCPtr, this);
    return (cPtr == 0) ? null : new LinkConfig(cPtr, false);
  }

  public void setVto(VtoConfig value) {
    javadnp3JNI.SlaveStackConfig_vto_set(swigCPtr, this, VtoConfig.getCPtr(value), value);
  }

  public VtoConfig getVto() {
    long cPtr = javadnp3JNI.SlaveStackConfig_vto_get(swigCPtr, this);
    return (cPtr == 0) ? null : new VtoConfig(cPtr, false);
  }

}
