/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.petrasolar.nms.protocol.dnp3;

public final class StackStates {
  public final static StackStates SS_COMMS_UP = new StackStates("SS_COMMS_UP");
  public final static StackStates SS_COMMS_DOWN = new StackStates("SS_COMMS_DOWN");
  public final static StackStates SS_UNKNOWN = new StackStates("SS_UNKNOWN");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static StackStates swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + StackStates.class + " with value " + swigValue);
  }

  private StackStates(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private StackStates(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private StackStates(String swigName, StackStates swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static StackStates[] swigValues = { SS_COMMS_UP, SS_COMMS_DOWN, SS_UNKNOWN };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

