/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.petrasolar.nms.protocol.dnp3;

public class Transaction {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected Transaction(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Transaction obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        javadnp3JNI.delete_Transaction(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public Transaction(ITransactable arTransactable) {
    this(javadnp3JNI.new_Transaction__SWIG_0(ITransactable.getCPtr(arTransactable), arTransactable), true);
  }

  public Transaction() {
    this(javadnp3JNI.new_Transaction__SWIG_1(), true);
  }

  public void Start(ITransactable apTransactable) {
    javadnp3JNI.Transaction_Start(swigCPtr, this, ITransactable.getCPtr(apTransactable), apTransactable);
  }

  public void End() {
    javadnp3JNI.Transaction_End(swigCPtr, this);
  }

}
