/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.petrasolar.nms.protocol.dnp3;

public class UnsignedPoint extends DataPoint {
  private long swigCPtr;

  protected UnsignedPoint(long cPtr, boolean cMemoryOwn) {
    super(javadnp3JNI.UnsignedPoint_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(UnsignedPoint obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        javadnp3JNI.delete_UnsignedPoint(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  protected void swigDirectorDisconnect() {
    swigCMemOwn = false;
    delete();
  }

  public void swigReleaseOwnership() {
    swigCMemOwn = false;
    javadnp3JNI.UnsignedPoint_change_ownership(this, swigCPtr, false);
  }

  public void swigTakeOwnership() {
    swigCMemOwn = true;
    javadnp3JNI.UnsignedPoint_change_ownership(this, swigCPtr, true);
  }

  public long GetValue() {
    return javadnp3JNI.UnsignedPoint_GetValue(swigCPtr, this);
  }

  public void SetValue(long aValue) {
    javadnp3JNI.UnsignedPoint_SetValue(swigCPtr, this, aValue);
  }

  public boolean ShouldGenerateEvent(UnsignedPoint arRHS, double aDeadband, long aLastReportedVal) {
    return javadnp3JNI.UnsignedPoint_ShouldGenerateEvent(swigCPtr, this, UnsignedPoint.getCPtr(arRHS), arRHS, aDeadband, aLastReportedVal);
  }

  public static long getMAX_VALUE() {
    return javadnp3JNI.UnsignedPoint_MAX_VALUE_get();
  }

  public static long getMIN_VALUE() {
    return javadnp3JNI.UnsignedPoint_MIN_VALUE_get();
  }

  public String ToString() {
    return (getClass() == UnsignedPoint.class) ? javadnp3JNI.UnsignedPoint_ToString(swigCPtr, this) : javadnp3JNI.UnsignedPoint_ToStringSwigExplicitUnsignedPoint(swigCPtr, this);
  }

  public boolean tdpEqual(UnsignedPoint rhs) {
    return javadnp3JNI.UnsignedPoint_tdpEqual(swigCPtr, this, UnsignedPoint.getCPtr(rhs), rhs);
  }

  protected UnsignedPoint(short aQuality, DataTypes aType) {
    this(javadnp3JNI.new_UnsignedPoint(aQuality, aType.swigValue()), true);
    javadnp3JNI.UnsignedPoint_director_connect(this, swigCPtr, swigCMemOwn, true);
  }

}
