/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.petrasolar.nms.protocol.dnp3;

public class VectorOfPointRecord {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected VectorOfPointRecord(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(VectorOfPointRecord obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        javadnp3JNI.delete_VectorOfPointRecord(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public VectorOfPointRecord() {
    this(javadnp3JNI.new_VectorOfPointRecord__SWIG_0(), true);
  }

  public VectorOfPointRecord(long n) {
    this(javadnp3JNI.new_VectorOfPointRecord__SWIG_1(n), true);
  }

  public long size() {
    return javadnp3JNI.VectorOfPointRecord_size(swigCPtr, this);
  }

  public long capacity() {
    return javadnp3JNI.VectorOfPointRecord_capacity(swigCPtr, this);
  }

  public void reserve(long n) {
    javadnp3JNI.VectorOfPointRecord_reserve(swigCPtr, this, n);
  }

  public boolean isEmpty() {
    return javadnp3JNI.VectorOfPointRecord_isEmpty(swigCPtr, this);
  }

  public void clear() {
    javadnp3JNI.VectorOfPointRecord_clear(swigCPtr, this);
  }

  public void add(PointRecord x) {
    javadnp3JNI.VectorOfPointRecord_add(swigCPtr, this, PointRecord.getCPtr(x), x);
  }

  public PointRecord get(int i) {
    return new PointRecord(javadnp3JNI.VectorOfPointRecord_get(swigCPtr, this, i), false);
  }

  public void set(int i, PointRecord val) {
    javadnp3JNI.VectorOfPointRecord_set(swigCPtr, this, i, PointRecord.getCPtr(val), val);
  }

}
