/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.petrasolar.nms.protocol.dnp3;

public class VectorOfControlRecord {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected VectorOfControlRecord(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(VectorOfControlRecord obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        javadnp3JNI.delete_VectorOfControlRecord(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public VectorOfControlRecord() {
    this(javadnp3JNI.new_VectorOfControlRecord__SWIG_0(), true);
  }

  public VectorOfControlRecord(long n) {
    this(javadnp3JNI.new_VectorOfControlRecord__SWIG_1(n), true);
  }

  public long size() {
    return javadnp3JNI.VectorOfControlRecord_size(swigCPtr, this);
  }

  public long capacity() {
    return javadnp3JNI.VectorOfControlRecord_capacity(swigCPtr, this);
  }

  public void reserve(long n) {
    javadnp3JNI.VectorOfControlRecord_reserve(swigCPtr, this, n);
  }

  public boolean isEmpty() {
    return javadnp3JNI.VectorOfControlRecord_isEmpty(swigCPtr, this);
  }

  public void clear() {
    javadnp3JNI.VectorOfControlRecord_clear(swigCPtr, this);
  }

  public void add(ControlRecord x) {
    javadnp3JNI.VectorOfControlRecord_add(swigCPtr, this, ControlRecord.getCPtr(x), x);
  }

  public ControlRecord get(int i) {
    return new ControlRecord(javadnp3JNI.VectorOfControlRecord_get(swigCPtr, this, i), false);
  }

  public void set(int i, ControlRecord val) {
    javadnp3JNI.VectorOfControlRecord_set(swigCPtr, this, i, ControlRecord.getCPtr(val), val);
  }

}
