/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.petrasolar.nms.protocol.dnp3;

public class VectorOfString {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected VectorOfString(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(VectorOfString obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        javadnp3JNI.delete_VectorOfString(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public VectorOfString() {
    this(javadnp3JNI.new_VectorOfString__SWIG_0(), true);
  }

  public VectorOfString(long n) {
    this(javadnp3JNI.new_VectorOfString__SWIG_1(n), true);
  }

  public long size() {
    return javadnp3JNI.VectorOfString_size(swigCPtr, this);
  }

  public long capacity() {
    return javadnp3JNI.VectorOfString_capacity(swigCPtr, this);
  }

  public void reserve(long n) {
    javadnp3JNI.VectorOfString_reserve(swigCPtr, this, n);
  }

  public boolean isEmpty() {
    return javadnp3JNI.VectorOfString_isEmpty(swigCPtr, this);
  }

  public void clear() {
    javadnp3JNI.VectorOfString_clear(swigCPtr, this);
  }

  public void add(String x) {
    javadnp3JNI.VectorOfString_add(swigCPtr, this, x);
  }

  public String get(int i) {
    return javadnp3JNI.VectorOfString_get(swigCPtr, this, i);
  }

  public void set(int i, String val) {
    javadnp3JNI.VectorOfString_set(swigCPtr, this, i, val);
  }

}
