/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.petrasolar.nms.protocol.dnp3;

public class VectorOfExceptionScan {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected VectorOfExceptionScan(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(VectorOfExceptionScan obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        javadnp3JNI.delete_VectorOfExceptionScan(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public VectorOfExceptionScan() {
    this(javadnp3JNI.new_VectorOfExceptionScan__SWIG_0(), true);
  }

  public VectorOfExceptionScan(long n) {
    this(javadnp3JNI.new_VectorOfExceptionScan__SWIG_1(n), true);
  }

  public long size() {
    return javadnp3JNI.VectorOfExceptionScan_size(swigCPtr, this);
  }

  public long capacity() {
    return javadnp3JNI.VectorOfExceptionScan_capacity(swigCPtr, this);
  }

  public void reserve(long n) {
    javadnp3JNI.VectorOfExceptionScan_reserve(swigCPtr, this, n);
  }

  public boolean isEmpty() {
    return javadnp3JNI.VectorOfExceptionScan_isEmpty(swigCPtr, this);
  }

  public void clear() {
    javadnp3JNI.VectorOfExceptionScan_clear(swigCPtr, this);
  }

  public void add(ExceptionScan x) {
    javadnp3JNI.VectorOfExceptionScan_add(swigCPtr, this, ExceptionScan.getCPtr(x), x);
  }

  public ExceptionScan get(int i) {
    return new ExceptionScan(javadnp3JNI.VectorOfExceptionScan_get(swigCPtr, this, i), false);
  }

  public void set(int i, ExceptionScan val) {
    javadnp3JNI.VectorOfExceptionScan_set(swigCPtr, this, i, ExceptionScan.getCPtr(val), val);
  }

}
