/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.petrasolar.nms.protocol.dnp3;

public class VectorOfDeadbandPointRecord {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected VectorOfDeadbandPointRecord(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(VectorOfDeadbandPointRecord obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        javadnp3JNI.delete_VectorOfDeadbandPointRecord(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public VectorOfDeadbandPointRecord() {
    this(javadnp3JNI.new_VectorOfDeadbandPointRecord__SWIG_0(), true);
  }

  public VectorOfDeadbandPointRecord(long n) {
    this(javadnp3JNI.new_VectorOfDeadbandPointRecord__SWIG_1(n), true);
  }

  public long size() {
    return javadnp3JNI.VectorOfDeadbandPointRecord_size(swigCPtr, this);
  }

  public long capacity() {
    return javadnp3JNI.VectorOfDeadbandPointRecord_capacity(swigCPtr, this);
  }

  public void reserve(long n) {
    javadnp3JNI.VectorOfDeadbandPointRecord_reserve(swigCPtr, this, n);
  }

  public boolean isEmpty() {
    return javadnp3JNI.VectorOfDeadbandPointRecord_isEmpty(swigCPtr, this);
  }

  public void clear() {
    javadnp3JNI.VectorOfDeadbandPointRecord_clear(swigCPtr, this);
  }

  public void add(DeadbandPointRecord x) {
    javadnp3JNI.VectorOfDeadbandPointRecord_add(swigCPtr, this, DeadbandPointRecord.getCPtr(x), x);
  }

  public DeadbandPointRecord get(int i) {
    return new DeadbandPointRecord(javadnp3JNI.VectorOfDeadbandPointRecord_get(swigCPtr, this, i), false);
  }

  public void set(int i, DeadbandPointRecord val) {
    javadnp3JNI.VectorOfDeadbandPointRecord_set(swigCPtr, this, i, DeadbandPointRecord.getCPtr(val), val);
  }

}
