/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.petrasolar.nms.protocol.dnp3;

public class VectorOfVtoRouterConfig {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected VectorOfVtoRouterConfig(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(VectorOfVtoRouterConfig obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        javadnp3JNI.delete_VectorOfVtoRouterConfig(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public VectorOfVtoRouterConfig() {
    this(javadnp3JNI.new_VectorOfVtoRouterConfig__SWIG_0(), true);
  }

  public VectorOfVtoRouterConfig(long n) {
    this(javadnp3JNI.new_VectorOfVtoRouterConfig__SWIG_1(n), true);
  }

  public long size() {
    return javadnp3JNI.VectorOfVtoRouterConfig_size(swigCPtr, this);
  }

  public long capacity() {
    return javadnp3JNI.VectorOfVtoRouterConfig_capacity(swigCPtr, this);
  }

  public void reserve(long n) {
    javadnp3JNI.VectorOfVtoRouterConfig_reserve(swigCPtr, this, n);
  }

  public boolean isEmpty() {
    return javadnp3JNI.VectorOfVtoRouterConfig_isEmpty(swigCPtr, this);
  }

  public void clear() {
    javadnp3JNI.VectorOfVtoRouterConfig_clear(swigCPtr, this);
  }

  public void add(VtoRouterConfig x) {
    javadnp3JNI.VectorOfVtoRouterConfig_add(swigCPtr, this, VtoRouterConfig.getCPtr(x), x);
  }

  public VtoRouterConfig get(int i) {
    return new VtoRouterConfig(javadnp3JNI.VectorOfVtoRouterConfig_get(swigCPtr, this, i), false);
  }

  public void set(int i, VtoRouterConfig val) {
    javadnp3JNI.VectorOfVtoRouterConfig_set(swigCPtr, this, i, VtoRouterConfig.getCPtr(val), val);
  }

}
