/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.petrasolar.nms.protocol.dnp3;

public class VectorOfEventPointRecord {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected VectorOfEventPointRecord(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(VectorOfEventPointRecord obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        javadnp3JNI.delete_VectorOfEventPointRecord(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public VectorOfEventPointRecord() {
    this(javadnp3JNI.new_VectorOfEventPointRecord__SWIG_0(), true);
  }

  public VectorOfEventPointRecord(long n) {
    this(javadnp3JNI.new_VectorOfEventPointRecord__SWIG_1(n), true);
  }

  public long size() {
    return javadnp3JNI.VectorOfEventPointRecord_size(swigCPtr, this);
  }

  public long capacity() {
    return javadnp3JNI.VectorOfEventPointRecord_capacity(swigCPtr, this);
  }

  public void reserve(long n) {
    javadnp3JNI.VectorOfEventPointRecord_reserve(swigCPtr, this, n);
  }

  public boolean isEmpty() {
    return javadnp3JNI.VectorOfEventPointRecord_isEmpty(swigCPtr, this);
  }

  public void clear() {
    javadnp3JNI.VectorOfEventPointRecord_clear(swigCPtr, this);
  }

  public void add(EventPointRecord x) {
    javadnp3JNI.VectorOfEventPointRecord_add(swigCPtr, this, EventPointRecord.getCPtr(x), x);
  }

  public EventPointRecord get(int i) {
    return new EventPointRecord(javadnp3JNI.VectorOfEventPointRecord_get(swigCPtr, this, i), false);
  }

  public void set(int i, EventPointRecord val) {
    javadnp3JNI.VectorOfEventPointRecord_set(swigCPtr, this, i, EventPointRecord.getCPtr(val), val);
  }

}
