/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.petrasolar.nms.protocol.dnp3;

public class VtoRouterSettings {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected VtoRouterSettings(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(VtoRouterSettings obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        javadnp3JNI.delete_VtoRouterSettings(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public VtoRouterSettings() {
    this(javadnp3JNI.new_VtoRouterSettings__SWIG_0(), true);
  }

  public VtoRouterSettings(short aChannelId, boolean aStartLocal, boolean aDisableExtensions, long aOpenRetryMs) {
    this(javadnp3JNI.new_VtoRouterSettings__SWIG_1(aChannelId, aStartLocal, aDisableExtensions, aOpenRetryMs), true);
  }

  public VtoRouterSettings(short aChannelId, boolean aStartLocal, boolean aDisableExtensions) {
    this(javadnp3JNI.new_VtoRouterSettings__SWIG_2(aChannelId, aStartLocal, aDisableExtensions), true);
  }

  public void setCHANNEL_ID(short value) {
    javadnp3JNI.VtoRouterSettings_CHANNEL_ID_set(swigCPtr, this, value);
  }

  public short getCHANNEL_ID() {
    return javadnp3JNI.VtoRouterSettings_CHANNEL_ID_get(swigCPtr, this);
  }

  public void setOPEN_RETRY_MS(long value) {
    javadnp3JNI.VtoRouterSettings_OPEN_RETRY_MS_set(swigCPtr, this, value);
  }

  public long getOPEN_RETRY_MS() {
    return javadnp3JNI.VtoRouterSettings_OPEN_RETRY_MS_get(swigCPtr, this);
  }

  public void setSTART_LOCAL(boolean value) {
    javadnp3JNI.VtoRouterSettings_START_LOCAL_set(swigCPtr, this, value);
  }

  public boolean getSTART_LOCAL() {
    return javadnp3JNI.VtoRouterSettings_START_LOCAL_get(swigCPtr, this);
  }

  public void setDISABLE_EXTENSIONS(boolean value) {
    javadnp3JNI.VtoRouterSettings_DISABLE_EXTENSIONS_set(swigCPtr, this, value);
  }

  public boolean getDISABLE_EXTENSIONS() {
    return javadnp3JNI.VtoRouterSettings_DISABLE_EXTENSIONS_get(swigCPtr, this);
  }

}
